# Generated by Django 5.1.7 on 2025-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuisine_dietaryrestriction_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
